### Create tag without error
POST http://127.0.0.1:3000/create-tag
Host: 127.0.0.1
Content-Type: application/json

{
    "product_code": "123-456-789"
}

### Create tag with error
POST http://127.0.0.1:3000/create-tag
Host: 127.0.0.1
Content-Type: application/json

{
    "invalid_param": "123-456-789"
}

###

POST http://127.0.0.1:3000/create-tag
Host: 127.0.0.1
Content-Type: application/json

{
    "product_code": 123456789
}